### ISSUE TITLE
config.proto changes too frequently to move to the service config

### ISSUE THREAD

**Issue by eoogbe** [googleapis/gapic-generator#1094]
And I don’t think the changes will settle. If a client adds a feature we didn’t anticipate, the gapic config will change again. We need to decide if merging the two configs is still a goal. If it is, we need the gapic config not to change when we add new features somehow.

**Comment by garrettjonesgoogle** [comment]
I don't quite understand what the problem is. Changes can either be additive (new config entries) or breaking (deletes, renames, type changes). If we restricted ourselves to additive changes when adding new features, I don't think there would be a problem.

**Comment by eoogbe** [comment]
I was of the understanding that merging with the service config required more stability than that

**Comment by garrettjonesgoogle** [comment]
@ethanbao do you have more insight on that?

**Comment by ethanbao** [comment]
I recommend that we merge the two configs once gapic config surface becomes stable, and will only have non-breaking changes.

**Comment by eoogbe** [comment]
What if the gapic config doesn't stabilize?

**Comment by ethanbao** [comment]
Then we need to figure out why it cannot be, even after the toolkit becomes GA quality.

**Comment by garrettjonesgoogle** [comment]
Back to my point about different types of changes: We can decide at some point to make the config.proto surface "GA", since that we only do additive changes after that point. I think it's a separate question of the rate of change: we could still have a lot of additive changes even after we declare that there are no new breaking changes. So at which point do we merge: after we declare the config surface frozen, or after the rate of change slows down?

**Comment by eoogbe** [comment]
Closing because gapic config should not be merged with service config

**Comment by eoogbe** [comment]
Reopening because the issue of whether the gapic config and the service config should be merged is not resolved.

**Comment by vchudnov-g** [comment]
Is this question still relevant, @eoogbe , given the proto annotations?
