### ISSUE TITLE
Fix Ruby proto doc formatting

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1287]
### Why

Some documentation markup is not rendering properly.

### What

Current state of things from, e.g., [error reporting docs](http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-error_reporting/v0.24.0/google/devtools/clouderrorreporting/v1beta1/deleteeventsrequest):
![dpsyug3wdkx](https://cloud.githubusercontent.com/assets/14222439/26332612/a7abe5ec-3f0c-11e7-817f-afe18d3edf31.png)

- The type should code-formatted, on the same line as, or clearly associated with, the text "Returns"
- There should be a newline between the type and the description
- The `+` delimiter should cause the delimited text to render in code format
- The markdown link should be parsed correctly

**Comment by geigerj** [comment]
Assigning to @landrito to provide a work estimate. Please feel free to unassign afterward if you don't have the bandwidth for this in the coming days.

**Comment by eoogbe** [comment]
@landrito Can you provide a work estimate?

**Comment by eoogbe** [comment]
- Return type: The page is showing `<h4>Returns</h4>` and combining the type with the next paragraph. The jsondoc is separating the description from the type, so the problem must be in the angular app.
- `+` for code: A transformer is changing all the backquotes to pluses. Just needs to be removed
- markdown link: errorreporting hasn't been regenerated since a fix to the links. It's a multiline link though, so the fix may be in changing the list generation logic in the `RubyCommentFormatter`. We should check that regeneration doesn't fix it first.

Side notes:
- Currently, the Ruby absolute link transformation is a noop. It should probably be axed.
- The transformer logic is still generally pretty bad. I'd like to change the `Transformation` function param to a `Matcher` so we quit matching patterns multiple times everywhere.

**Comment by andreamlin** [comment]
@landrito @eoogbe friendly ping on this
Is this still a P1?

**Comment by landrito** [comment]
I think this has been fixed but this issue wasn't updated. Give me a day to track it down!

**Comment by andreamlin** [comment]
@landrito Updates?

**Comment by landrito** [comment]
So the work items I see are:

- [ ] The type should code-formatted, on the same line as, or clearly associated with, the text "Returns"
  - @eoogbe addressed this in: https://github.com/googleapis/gapic-generator/issues/1287#issuecomment-341302264
- [ ] There should be a newline between the type and the description
  - This has been fixed but I am failing to find the PR.
- [ ] The + delimiter should cause the delimited text to render in code format
  - This has been fixed but I am failing to find the PR.
- [ ] The markdown link should be parsed correctly
  - This has been fixed in https://github.com/googleapis/gapic-generator/pull/1334

**Comment by landrito** [comment]
Closing as all the items have been addressed.
