### ISSUE TITLE
Ruby: Investigate suspected doc regression

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator#1678]
### What

Investigate whether a code generator bug is suppressing documentation output for certain types.

### Context

A GAPIC refresh caused documentation for certain enum types to disappear. See https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1804#discussion_r150072904, https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1727#discussion_r139265901.

**Comment by geigerj** [comment]
The specific case in the context (loss of documentation for the enum `google.iam.v1.BindingDelta.Action`) appears to be caused by that type failing a reachability check in [GrpcElementDocTransformer](https://github.com/googleapis/toolkit/blob/d395fdb0fb1c557054e748dafe564a35804f18db/src/main/java/com/google/api/codegen/transformer/GrpcElementDocTransformer.java#L83). @eoogbe added this check during an MVVM port.

Follow up questions:
- What effect does documenting unreachable enums have on the output of languages other than Ruby?
- Why would we document an unreachable message but not document the enum types it contains? (My intuition is: this should not happen. If there needs to be a reachability condition, it should be checked on the container, and not on the enum.)

@eoogbe Do you recall the context for adding this check?

**Comment by eoogbe** [comment]
> What effect does documenting unreachable enums have on the output of languages other than Ruby?

- NodeJS: Same as Ruby (i.e. adds documentation for unreachable enums)
- Python: Adds every unreachable enum in all the files under the model to `enums.py`

> Why would we document an unreachable message but not document the enum types it contains?

From my understanding of reachability, an unreachable type should not be publicly documented. Right now, we only enforce that for enums We need to also enforce that for messages. Because the container for a top-level enum is a file, not a message, we need to add checks for unreachable messages, rather than replace the existing checks on the enums.

> Do you recall the context for adding this check?

Not very well. I think I needed it to keep the tests passing when I migrated Python to MVVM. Without it, Python will generate a ton of enums that weren't getting generated before MVVM migration.

Looking into it more, we do need to check reachability somewhere to generate the enums correctly. For Python, reachability is only checked at the enum level. This is sufficient because we only generate enums in `enums.py`, not messages. For Ruby and NodeJS, reachability is checked for enums but not for messages. We should fix this inconsistency by checking messages as well.

**Comment by geigerj** [comment]
> From my understanding of reachability, an unreachable type should not be publicly documented. Right now, we only enforce that for enums We need to also enforce that for messages.

Ack. This sounds like the right approach to me, too.
