### ISSUE TITLE
Python enum classes should provide a way to get the string name of a value

### ISSUE THREAD

**Issue by theacodes** [googleapis/gapic-generator#1866]
When working with enums, you often just get back a number from the API, for example:

```
response = my_api.MyMethod()
print(response.some_enum)
# 4
```

Right now if you want to turn that number into a nice, human-readable string you gotta do some craziness like this:

```
types.SomeResponseType.DESCRIPTOR.fields_by_name['some_enum'].enum_type.values_by_number[4].name
```

Since we already generate friendly enum classes, can we add a method to grab the string name from the numeric value? I'm flexible on the name `name_by_value` works.

**Comment by lukesneeringer** [comment]
Honestly, I would really love to change this to use `enum` from the standard library (and `enum34` in Python 2.7), but it would be a backwards incompatible change. Also, to really do it right, it would have to be in protobuf.

Since that is out of bounds at the moment, I agree with having a method on the enum classes that does that thing. I would prefer name it whatever it is called in the `enums` stdlib package.

**Comment by lukesneeringer** [comment]
Bah, there is no converse of `__members__`. Something like what you proposed is fine.

**Comment by jonparrott** [comment]
> but it would be a backwards incompatible change.

Love it, let's do that. 

> but it would be a backwards incompatible change

How so? 

> I would prefer name it whatever it is called in the enums stdlib package.

Agree, but it's actually not that easy to emulate without just using enum. The interface is:

```
print(enums.SomeEnum(4).name)
# SOME_VALUE
```

Or just

```
print(enums.SomeEnum(4))
# <SomeEnum.SOME_VALUE: 4>
```

**Comment by jonparrott** [comment]
This has been identified multiple times as a significant user experience issue for Python clients. Please prioritize accordingly.

**Comment by lukesneeringer** [comment]
@jonparrott I am so sorry, I lost track of this.

The reason why I said it would be a backwards incompatible change is because right now someone might do:

```python
from foo.bar import enums
if value_from_thing == enums.EnumType.ENUM_VALUE:
    [...]
```

And that is not how enum classes from Python 3.4 enums work. If we changed it so that we _output_ the enum values, then anyone who was previously using `== 4` (as an example) would break.

If there is a way to make this change though, I would really love to do it.

**Comment by jonparrott** [comment]
[IntEnum](https://docs.python.org/3/library/enum.html#enum.IntEnum) exists exactly for this purpose.
