### ISSUE TITLE
Optional args conflicts in dynamic languages

### ISSUE THREAD

**Issue by michaelbausor** [googleapis/gapic-generator#1983]
If a proto field on the request message has the same name as an optional argument such as `timeout`, there is a conflict in some of the dynamic languages.

PHP and Python are definitely affected; Node and Ruby seem OK, but folks who know those languages better should also weigh in.

Here is a dummy PR showing baselines when a request message contains problematic fields: https://github.com/googleapis/gapic-generator/pull/1981

**Comment by vchudnov-g** [comment]
Is this still an issue?

**Comment by michaelbausor** [comment]
Yes. But I believe that it is not affecting any APIs at this time, so there isn't pressure to fix it in the short term.

**Comment by eoogbe** [comment]
@michaelbausor Any updates?

**Comment by michaelbausor** [comment]
No updates. We are unlikely to fix without a motivating case.

**Comment by noahdietz** [comment]
Per the last comment, without a motivating case, we will not prioritize this work. I am closing this as "won't fix" because it is out of SLO. The issue being here is documentation that the problem exists and our reasoning for not addressing it. We can reopen and address it when an error scenario arises.
