### ISSUE TITLE
Node.js: UnhandledPromiseRejection in createStub when keyfile path doesn't exist

### ISSUE THREAD

**Issue by kinwa91** [googleapis/gapic-generator#2065]
Original issue https://github.com/googleapis/nodejs-text-to-speech/issues/12

Promise rejection from [createStub](https://github.com/googleapis/gax-nodejs/blob/da7a0bd4001f6cbe42d198e52e8ad3896d3d461f/src/grpc.ts#L257-L281) (due to missing auth keyfile, etc..) is not caught, causing UnhandledPromiseRejection warning:

https://github.com/googleapis/gapic-generator/blob/55975094fff73249d12052dfe0f4622b79eb67dd/src/main/resources/com/google/api/codegen/nodejs/main.snip#L224-L229

We should `.catch` and `process.exit` when client fails to initialize.

**Comment by alexander-fenster** [comment]
We must not `process.exit` since it's a bad behavior for library. Actually, I'm not convinced that we must catch the exception since it's obviously the user error, not the network / server error that we retry on. Catching exceptions just to `console.log` them isn't valuable either because we can't `console.log` in the library. So, assume we caught an exception from `gaxGrpc.createStub`, what next?

I feel it might be the place where just doing nothing is good enough. Thoughts?

@JustinBeckwith @ofrobots

**Comment by JustinBeckwith** [comment]
I think the error described in the original issue was fine.  I'm not sure if there's much else we could have done.  @ofrobots thoughts?

**Comment by ofrobots** [comment]
Is there a way for the user to have handled the unhandled rejections? If not it is bad form for a library to generate unhandle-able rejections. It is even /worse/ form for a library to use `process.exit`.

I don't understand the choreography of events between the library, client library, gax stubs and grpc, but at a high level, it seems to be that we let an operation - that had no chance of success – happen. An error should have been thrown a lot earlier. However, since I don't know the implementation details, I can't provide specific solutions.

**Comment by murrayju** [comment]
It is bad practice for a library to throw errors that the user cannot possibly catch. In this case, the constructor is doing some async operation, and not handling the error case. Because it is async, invoking the constructor within a try/catch block doesn't help.

There are several ways that this could be fixed. I would suggest either:
1. Catch the promise rejection internally, then expose the error to the user through some other mechanism (e.g. make the class an `EventEmitter` and emit an error event, set some internal flag and throw when api methods are called)
2. Expose a handle to the promise in question, allowing the user to register their own catch

This should be considered a critical bug. I find it incredibly risky to use a library that crashes the entire application process when passed bad configuration values.

**Comment by vchudnov-g** [comment]
@alexander-fenster ping

**Comment by vchudnov-g** [comment]
@alexander-fenster ping

**Comment by noahdietz** [comment]
@alexander-fenster any update? Thanks!

**Comment by andreamlin** [comment]
@alexander-fenster hey how's this going?

**Comment by jbolinger** [comment]
@alexander-fenster any news?

**Comment by landrito** [comment]
@alexander-fenster any updates?

**Comment by kidplug** [comment]
Any attention being given to this?

**Comment by alexander-fenster** [comment]
@kidplug @murrayju Sorry, it took longer than expected. I originally planned to fix it in the new generator but since it's a quick and easy fix (please review what I suggest to change), let's just do it here and now. It will take several weeks for this fix to get into all libraries but eventually you'll find it there.
