### ISSUE TITLE
[Ruby] Generated version module file includes documentation for outer service module

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2123]
The Ruby generator generates an "outer" module named for the service, and inner modules named for the versions. e.g. `lib/google/cloud/speech.rb` and `lib/google/cloud/speech/v1.rb`. By convention, the file name should match the "main" class/module being defined (and documented) in the file. Thus, we expect that `lib/google/cloud/speech.rb` will include the definition and documentation for `Google::Cloud::Speech`, and we expect `lib/google/cloud/speech/v1.rb` to include the definition and documentation for `Google::Cloud::Speech::V1`. However, currently, the `lib/google/cloud/speech/v1.rb` file includes the documentation for `Google::Cloud::Speech`. That is, the module `Google::Cloud::Speech` is documented (identically) in _both_ files.

**Comment by jbolinger** [comment]
@dazuma this was before my time, but I believe the duplication was intentional. Not really sure if I recall why but I think it was so the "quick start" was in both files. However, this is in your court now so if you don't think that's a good reason I'm happy to change it.

Just to clarify, you are saying that the correct thing to do is to simply omit that text block for `Google::Cloud::Speech` in the file `lib/google/cloud/speech/v1.rb`?

**Comment by dazuma** [comment]
Sorry, I failed to make it clear what I think needs to be done.

It's okay to have the content duplicated. But in `v1.rb`, the comment should be tied to the `V1` module. Currently it is tied to the `Speech` module in that file. (It should, of course, remain tied to the `Speech` module in `speech.rb`.

**Comment by jbolinger** [comment]
Ah, that makes sense. I'll move it.
