### ISSUE TITLE
Order of entries in generated 'enums' is not stable

### ISSUE THREAD

**Issue by tseaver** [googleapis/gapic-generator#2319]
E.g., see: https://github.com/GoogleCloudPlatform/google-cloud-python/pull/6015/files.

The order should match the order in the `.proto` file, except that they might be collected from more than one:  if that case in general, then sort them.

**Comment by tseaver** [comment]
Another example today:  https://github.com/GoogleCloudPlatform/google-cloud-python/pull/6109/files

**Comment by tseaver** [comment]
@JustinBeckwith, @theacodes per today's call.

**Comment by theacodes** [comment]
@lukesneeringer @andreamlin any more information we can provide here?

**Comment by tseaver** [comment]
Any update here?

**Comment by lukesneeringer** [comment]
Hey folks, one question: Is the order _non-deterministic_ or did the order remain deterministic and change?

I think this change may have been caused by some work done to sort other components (not specific to Python).

**Comment by andreamlin** [comment]
Thanks for reporting this.

Forewarning: I'm not a Python expert.

1. for PR https://github.com/GoogleCloudPlatform/google-cloud-python/pull/6015/files, I can't see what the change is, besides that the order of class defs is swapped. Does this matter, given that the classes don't reference each other?

2. For the requirement that "The order should match the order in the .proto file, except that they might be collected from more than one: if that case in general, then sort them.":
Assuming the class order does matter, wouldn't it be a breaking change to introduce a new protofile when there was only one protofile before? The order would get rearranged because now they're being sorted.

**Comment by andreamlin** [comment]
Talked to Luke offline.
1. Confirming that the PRs are annoying changes, but this isn't a semantic change?

**Comment by andreamlin** [comment]
@vam-google Would https://github.com/googleapis/googleapis/blame/master/google/bigtable/admin/v2/BUILD.bazel have to do with this? Since that explicitly lists out the order in which the proto files are given to gapic-generator.

**Comment by lukesneeringer** [comment]
Would it be possible to update this specific Bazel build file to match what was in the legacy configuration (which would theoretically revert the enum sort order in Bigtable)?

**Comment by andreamlin** [comment]
Talked to @vam-google and it can't be related because that BUILD file was pushed after this issue was filed.

I've been looking at how we generate the enum classes, and it seems to come from the order the proto files are passed in. This seems like a deterministic order. However, as Luke mentioned, we have been going through some refactorings that change the the order of surface entities in the clients. This churn should settle down in a while.

**Comment by tseaver** [comment]
This is not a case of one-time changes:  I've seen multiple autosynth-driven PRs which do nothing more than change enum order:  approving one doesn't make the problem go away.  When I run synthtool on my machine, I have gotten a different order than the one in the autosynth PR.

Note that I don't really care about any specific order, only that it be stable over time.

**Comment by tseaver** [comment]
This mornings autosynth runs still have this issue:

- https://github.com/googleapis/google-cloud-python/pull/6474
- https://github.com/googleapis/google-cloud-python/pull/6475
- https://github.com/googleapis/google-cloud-python/pull/6476

**Comment by tseaver** [comment]
@andreamlin I don't know how to tell if the change from #2418 has actually been rolled out to the artman image:  is there some way to check locally using synthtool?

**Comment by tseaver** [comment]
I believe this issue is now closed, although, like Ahrnuld, "I'll be back!" if it pops up again in future autosynth runs.

**Comment by tseaver** [comment]
Sigh.

**Comment by tseaver** [comment]
New incidences today:

- https://github.com/googleapis/google-cloud-python/pull/6636
- https://github.com/googleapis/google-cloud-python/pull/6637
- https://github.com/googleapis/google-cloud-python/pull/6638
- https://github.com/googleapis/google-cloud-python/pull/6639

**Comment by tseaver** [comment]
@andreamlin Is there a way we could just sort the top-level enums / messages by name, and sort the enums within messages by name?  I can't see a way to get that done, looking at `transformer/py/PythonGapicSurfaceTransformer.java` or `transformer/GrpcElementDocTransformer.java`.

**Comment by andreamlin** [comment]
@tseaver Sure, if we're fine with a one-time change to the surface that orders all existing enums. I can give it a shot

**Comment by andreamlin** [comment]
@tseaver See https://github.com/googleapis/gapic-generator/pull/2453 for a fix and https://github.com/googleapis/google-cloud-python/pull/6707 for an example of what happens after that PR is applied.
