### ISSUE TITLE
SampleGen: update Ruby snippets to match official googleapis/ruby-style

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2812]
Style and accompanying lint configuration file: [googleapis/ruby-style](https://github.com/googleapis/ruby-style)
Run lint the code, follow instructions in README of [googleapis/ruby-style](https://github.com/googleapis/ruby-style)

As reported by: https://github.com/googleapis/google-cloud-ruby/pull/3431#issuecomment-498772695

/cc @googleapis/samplegen 
/fyi @TheRoyalTnetennba @dazuma @quartzmo

**Comment by hzyi-google** [comment]
Porting over comments in the linked issue that involves work items in gapic-generator:

These errors can and should be fixed in the generator (nice catch, good bot!):

- [ ] - Final newline missing
- [ ] - method def using parentheses
- [ ] - prefers $PROGRAM_NAME over $0
- [ ] - incorrect indentation for comments
