### ISSUE TITLE
Java: Naming conflict (java template)

### ISSUE THREAD

**Issue by munkhuushmgl** [googleapis/gapic-generator#2854]
![image](https://user-images.githubusercontent.com/45373284/60044838-1be8e300-9678-11e9-99f9-f424e7073779.png)

**Comment by vam-google** [comment]
@munkhuushmgl Please provide more details about the issue. I can see that dataset is defined twice in your screenshot, but we need more details. 

What exactly is this (client code or samples code)? 
How was it generated? 
What are the .protos and gapic.yamls used to generated it? 

But in general the naming conflicts are possible not only in gapic-generator but in protoc itself, unfortunately. 

Sometimes, in very rare corner cases, naming conflicts are unavoidable and fixing them would be worse than keeping as is (so the solution would be just to rename something in the API itself, so the conflict goes away). This is also always possible to make generators generate confclicting names if the config itself contains conflicting names (in this case the generated code just inherits a bug introduced in the config file). That is why we need more info to figure out where the problem is.

**Comment by munkhuushmgl** [comment]
What exactly is this (client code or samples code)? **sample code**
How was it generated? **Generated by SYNTHTOOL GAPIC **
What are the .protos and gapic.yamls used to generated it? **.yaml --> googleapis/google/cloud/automl/v1beta1/automl_gapic **

If you need any more info, please let me know

**Comment by hzyi-google** [comment]
I think we should explicitly fail in this case. Thoughts? @vchudnov-g @beccasaurus

**Comment by software-dov** [comment]
Bump for open bug @hzyi-google @beccasaurus @vchudnov-g

**Comment by hzyi-google** [comment]
Let's make sure this goes into v1.3.

**Comment by hzyi-google** [comment]
moved to backlog: https://github.com/googleapis/gapic-generator/wiki/feature-backlog/
