### ISSUE TITLE
Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by tamngonesv030** [googleapis/gapic-generator#3013]
I'm using google api for Server java: 
InputStream inputStream = new ByteArrayInputStream(serviceAccountContent.getBytes());
 credential =GoogleCredential.fromStream(inputStream).createScoped(Collections.singleton(AndroidPublisherScopes.ANDROIDPUBLISHER));

String endPoint = "https://indexing.googleapis.com/v3/urlNotifications:publish";
            GenericUrl genericUrl = new GenericUrl(endPoint);
            HttpRequestFactory requestFactory = this.HTTP_TRANSPORT.createRequestFactory();

            // Define content here. The structure of the content is described in the next step.
            String content = "{"
              + "\"url\": \"http://myweb.com/jobs/42\","
              + "\"type\": \"URL_UPDATED\","
              + "}";

            HttpRequest request =
              requestFactory.buildPostRequest(genericUrl, ByteArrayContent.fromString("application/json", content));

            getCredential().initialize(request);
            HttpResponse response = request.execute();
            int statusCode = response.getStatusCode();

I receice message: please help me !

{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "errors": [
      {
        "message": "Request had insufficient authentication scopes.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}

**Comment by vam-google** [comment]
Hi @tamngonesv030. Can you please clarify your issue. This is a client generator repository - a tool, which generates gRPC-based clients for google api. The issue description looks more like an Authentication problem and probably belongs to https://github.com/googleapis/google-auth-library-java/issues. 

If you do not experience issues with the generator itself, please close the issue here and reopen it in a proper repository (google-auth-library-java could be the correct place for it).
