### ISSUE TITLE
Java: breaking change when `operation_info` annotation is added to a method

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#3168]
Case in point: https://github.com/googleapis/java-cloudbuild/pull/128

For now, if an LRO method does not have `google.longrunning.operation_info` annotation, the generator treats it as a normal unary call. This would lead to breaking changes when the `operation_info` is added to an LRO method. To solve this, we should either:

1) fail if a method returning `google.longrunning.Operation` does not have `operation_info` annotation.
2) generate backward-compatible code if `operation_info` is added to an LRO method, i.e., generate the unary method too.

(1) should be preferable as it's both easier and generates less "useless" code. That means we will need to take a major bump to cloudbuild.

**Comment by miraleung** [comment]
Summarizing a discussion with @vam-google: Doing nothing is probably the best approach. Here's an analysis of the approaches:

1. This approach will break firestore, cloudbuild, dialogflow, gameservices, and vision (the last of which is in GA).
2. This will generate many more unused methods.
3. Doing nothing achieves the best tradeoff between #1 and #2, and breaks the least number of clients (just cloudbuild).

**Comment by hzyi-google** [comment]
Soooo if we do nothing, cloudbuild generation will not break but it will still has breaking changes (The return type changed for this specific method). 

It may be worth considering continuing with 1 and whitelist the 5 APIs in the generator (a.k.a hard-coding). We can't avoid breaking changes for them but it will prevent other APIs from ending up in the same situation as the 5 APIs listed above.

**Comment by miraleung** [comment]
@vam-google

**Comment by vam-google** [comment]
@miraleung I don't like option 2, as it bloats the client surface even more (btw, if we add it, it will immediately generate many new methods on all of our existing clients which have LRO methods, many of which are GA; it will be a non-breaking change, but a massive and weird one). 

Option 1 is Ok, I just feel uncomfortable hard-codding client names in generic tool (which gapic-generator is). 

If you guys (@hzyi-google and @miraleung) feel strong about doing it (option 1 + hardcode), I'm Ok, with it. 

The way I look at it is that this kind of stuff should be in API design guidelines, and instead of us trying to workaround all possible incompatibility issues, it should be clearly stated that it is a breaking change. 

Also I'm not sure how legit is having LRO api method without specified metadata (i.e. maybe it is ok, and exactly what API owners want).

When I think about all this, I keep coming back to the idea the maybe doing nothing is the best thing here.

**Comment by hzyi-google** [comment]
> I'm not sure how legit is having LRO api method without specified metadata (i.e. maybe it is ok, and exactly what API owners want)

It's strictly disallowed: https://aip.dev/151#guidance

**Comment by vam-google** [comment]
@hzyi-google Ok, then failing is good. Hardcodding - I can pretend that i did not see it during review =)

**Comment by hzyi-google** [comment]
They are not hard-coded, they are prearranged :)

**Comment by miraleung** [comment]
After digging into this a bit more, doing nothing seems to be an optimal approach because:

- The whitelisting mechanism would be brittle and error-prone. We can only rely on string-searching response, return, and metadata types in the method in question.
- We may have to support these in the new microgenerator.
- Cloudbuild will have a breakage either way.

Please LMK what you think. If there's a strong need for a fix, let's reopen the issue.

For posterity, here is the list of breakages under option 1:

- Firestore: v1beta2 only
- Dialogflow: v2beta1 only
- Cloudbuild: This will have a breakage no matter which approach we take, due to the annotations being added after the fact. Since they added `google.longrunning.operation_info` after the fact, this should be considered a breaking change.
- Vision: Should be fine
- Gameservices: Ditto, should be fine.

**Comment by vam-google** [comment]
LGTM
