### ISSUE TITLE
Changed layout of `java_gapic_assembly_gradle_pkg` output

### ISSUE THREAD

**Issue by aohren** [googleapis/gapic-generator#3264]
The output file hierarchy of .tar.gz files produced by `java_gapic_assembly_gradle_pkg` has changed again (similar to #3249), though at least this time it doesn't appear to be as broken. But all the `*ServiceGrpc.java` classes appear to have been moved to their own top-level folder. 

Before, we had:
```
.
├── gapic-googleads-java
├── gradle
└── proto-googleads-java
```

Now we have a new top-level `grpc-googleads-java` folder, and all the `*ServiceGrpc.java` files have moved from `gapic-googleads-java` to `grpc-googleads-java`: 
```
.
├── gapic-googleads-java
├── gradle
├── grpc-googleads-java
└── proto-googleads-java
```

Was this intentional?

**Comment by vam-google** [comment]
The new structure is correct, the old one was incorrect. All cloud client have always had the new structure. The difference is not caused by changes in the `java_gapic_assembly_pkg`, but by the recent change in the grpc target naming in ads (i.e. change from `java_grpc` target name to `<service>_<lang>_grpc` target name). Unless the target was named `<service>_<lang>_grpc` it was not recognized by the assembly rule as an actual grpc target and that is why it was not put in a separate grpc module. 

It works as intended.
