### ISSUE TITLE
_doc does not generate the documents for mixin protos

### ISSUE THREAD

**Issue by jmuk** [googleapis/gapic-generator#603]
`python_doc_message_library.baseline`, `ruby_doc_message_library.baseline`, and `nodejs_doc_message_library.baseline` don't have any references about tagger.proto. It seems the message generator does nothing on the mixin protos.

This would be problematic when generating documents for pubsub. Cc: @geigerj @bjwatson @swcloud

**Comment by geigerj** [comment]
Presumably this is only for `reroute_to_grpc` fields and not for properly declared mixins? If it's also for properly declared mixins, that's surprising and merits some investigation.

For `reroute_to_grpc`, we should change the implementation of [`ProtoFileView`](https://github.com/googleapis/toolkit/blob/f912ff7667d023145e6340e6824f15c4938df1bd/src/main/java/com/google/api/codegen/ProtoFileView.java#L41) so that instead of getting methods from `Model` it instead gets them from `ApiConfig`. This might require some refactoring as the `XXXView` classes are currently structured to get `XXX` from `Model`.

**Comment by eoogbe** [comment]
@geigerj Can you assign someone to this P1 issue?

**Comment by eoogbe** [comment]
Should mixin interfaces be defined in the gapic config?
