### ISSUE TITLE
Add unit tests for CommentPatterns regular expressions

### ISSUE THREAD

**Issue by swcloud** [googleapis/gapic-generator#722]
While fixing #716, we found that there are no comprehensive unit test that are written for the following classes:

CommentPatterns.java
RDocCommentFixer.java
PythonSphinxCommentFixer.java
JSDocCommentFixer.java

While #716 PR provides unit tests for the above classes for its specific issues, these classes should have more comprehensive unit tests.

**Comment by eoogbe** [comment]
This should now be the CommentReformatters.

**Comment by geigerj** [comment]
Ack. Specifically, if I recall correctly, the context was that the regexes were quite complicated and some test cases would have helped, so that would mean testing [CommentPatterns](https://github.com/googleapis/toolkit/blob/d31e0d89453f19511d34aa60e10171da0193bd59/src/main/java/com/google/api/codegen/CommentPatterns.java).

**Comment by eoogbe** [comment]
Obsolete since we are migrating to microgenerators
